# Generated by Django 2.2.16 on 2023-04-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dopolneniya',
            field=models.ManyToManyField(to='shop.Dopolnenie'),
        ),
    ]
