# Generated by Django 2.2.16 on 2023-04-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_dopolneniya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dopolnenie',
            name='dop1',
        ),
        migrations.AddField(
            model_name='dopolnenie',
            name='category',
            field=models.CharField(db_index=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dopolnenie',
            name='available_dop1',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dopolnenie',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dopolnenie',
            name='price_dop1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
