# Generated by Django 2.2.16 on 2023-04-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20230427_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='dop',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dop',
            name='dop1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dop',
            name='dop2',
            field=models.CharField(max_length=20),
        ),
    ]
