# Generated by Django 2.2.16 on 2023-04-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20230427_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='dop',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dop3', to='shop.Product'),
        ),
    ]
