# Generated by Django 2.2.16 on 2023-04-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_dop_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dop',
            new_name='Dopolnenie',
        ),
        migrations.RenameField(
            model_name='dopolnenie',
            old_name='dop1',
            new_name='dopoln1',
        ),
        migrations.RenameField(
            model_name='dopolnenie',
            old_name='dop2',
            new_name='dopoln2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dop',
        ),
        migrations.AddField(
            model_name='product',
            name='dopolnenie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.Dopolnenie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.Category'),
        ),
    ]
