# Generated by Django 2.2.16 on 2023-04-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230427_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopolnenie',
            name='price_dop1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dopolnenie',
            name='price_dop2',
            field=models.BooleanField(default=False),
        ),
    ]
