# Generated by Django 2.2.16 on 2023-04-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20230427_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dopolnenie',
            old_name='price_dop2',
            new_name='available_dop1',
        ),
        migrations.RenameField(
            model_name='dopolnenie',
            old_name='dopoln1',
            new_name='dop1',
        ),
        migrations.RemoveField(
            model_name='dopolnenie',
            name='dopoln2',
        ),
        migrations.AlterField(
            model_name='dopolnenie',
            name='price_dop1',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
