# Generated by Django 2.2.16 on 2023-04-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20230427_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='dopolnenie',
            name='prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dopolnenies', to='shop.Product'),
        ),
    ]
