# Generated by Django 2.2.16 on 2023-04-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_dopolnenie_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
