# Generated by Django 2.2.16 on 2023-04-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('N', 'Наличные'), ('C', 'Картой'), ('D', 'Депозит')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
